// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhpAwtj4x3qkF8E-ceRdJu37Q_sGhuz8',
    appId: '1:262135090775:web:201141a1dad4a8b0eb9d12',
    messagingSenderId: '262135090775',
    projectId: 'chakra-cabs-439820',
    authDomain: 'chakra-cabs-439820.firebaseapp.com',
    storageBucket: 'chakra-cabs-439820.firebasestorage.app',
    measurementId: 'G-39M82Z6SQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpcq2CQ3Qmj0LZwmb04YAzniKPQELRws',
    appId: '1:262135090775:android:58c704818a8eba81eb9d12',
    messagingSenderId: '262135090775',
    projectId: 'chakra-cabs-439820',
    storageBucket: 'chakra-cabs-439820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWW1p1MdZlodmlfHmeOXTGmycKJAXJg74',
    appId: '1:262135090775:ios:464c96df614b1ca3eb9d12',
    messagingSenderId: '262135090775',
    projectId: 'chakra-cabs-439820',
    storageBucket: 'chakra-cabs-439820.firebasestorage.app',
    iosBundleId: 'com.chakracabs.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWW1p1MdZlodmlfHmeOXTGmycKJAXJg74',
    appId: '1:262135090775:ios:464c96df614b1ca3eb9d12',
    messagingSenderId: '262135090775',
    projectId: 'chakra-cabs-439820',
    storageBucket: 'chakra-cabs-439820.firebasestorage.app',
    iosBundleId: 'com.chakracabs.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZhpAwtj4x3qkF8E-ceRdJu37Q_sGhuz8',
    appId: '1:262135090775:web:7ed533b877f09e29eb9d12',
    messagingSenderId: '262135090775',
    projectId: 'chakra-cabs-439820',
    authDomain: 'chakra-cabs-439820.firebaseapp.com',
    storageBucket: 'chakra-cabs-439820.firebasestorage.app',
    measurementId: 'G-XQ1SJMNRTP',
  );
}
